### ISSUE TITLE
Day 1 - Store Concept

### ISSUE THREAD

**Issue by ItsY8S** [ItsY8S/wai#1]
## Artist Merchandise Store

This application is a content management system that allows music artists to sell merchandise on a personalized store. Artists looking to take the next step can get their products out into the world in just a few easy clicks.

### Technologies
- [Node.js](https://nodejs.org/)
- [React.js](https://reactjs.org/)
- [MongoDB](https://www.mongodb.com/)
- [Heroku](https://www.heroku.com/)
- [Skeleton](http://getskeleton.com/)

### Similar Services
- [Shopify](https://www.shopify.com/)
- [Big Cartel](https://www.bigcartel.com/)
- [Etsy](https://www.etsy.com/)
- [WooCommerce](https://woocommerce.com/)
- [Facebook Marketplace](https://www.facebook.com/marketplace/)

### Target Audience
- Age (Recommended 16+)
- All genres
- Established artists with a decent-sized following

### Ideas / Features
- OAuth (SoundCloud, Spotify, etc...)
- Store customization (header image, color theme)
- Search (products)
- Filter / Sort

**Comment by brandonbrown** [comment]
Hey Griffin.

The "Good First Issue" label is one normally saved for helping people new to a project or to coding quickly find a way to contribute. I would recommend a different label here. "Planning" or "Project Concept" could be useful.

**Comment by brandonbrown** [comment]
Are you only pitching the store concept, or should I expect to see more concepts put in?

**Comment by brandonbrown** [comment]
Store concept approved. Work towards full documentation and feature set should be in process.
